version: "3.7"
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - my_network
  grafana:
    image: grafana/grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
      - "./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources"
      - "./docker/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards"
    ports:
      - "3000:3000"
    networks:
      - my_network
    depends_on:
      - prometheus
  eureka-discovery-service:
    image: openjdk:11
    volumes:
      - ./discovery/build/libs:/app
    ports:
      - "8761:8761"
    command: java -jar /app/discovery-0.0.1-SNAPSHOT.jar
    networks:
      - my_network
  admin-server-service:
    image: openjdk:11
    volumes:
      - ./admin-server/build/libs:/app
    ports:
      - "9000:9000"
    command: java -jar /app/admin-server-0.0.1-SNAPSHOT.jar
    networks:
      - my_network
  gateway-service:
    image: openjdk:11
    volumes:
      - ./gateway/build/libs:/app
    ports:
      - "8080:8080"
    command: java -jar /app/gateway-0.0.1-SNAPSHOT.jar
    networks:
      - my_network
  to-do-list-service:
    image: openjdk:11
    volumes:
      - ./todolist/build/libs/todolist-0.0.1-SNAPSHOT.jar:/app/todolist-0.0.1-SNAPSHOT.jar
      - ./docker/wait-for-it.sh:/wait-for-it.sh
    ports:
      - "10000:10000"
    entrypoint: ["/wait-for-it.sh", "db:3306", "--", "java", "-jar", "/app/todolist-0.0.1-SNAPSHOT.jar"]
    networks:
      - my_network
  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskdb
    networks:
      - my_network

networks:
  my_network:
    external:
      name: my_network