version: "3.7"
services:
  eureka-discovery-service:
    image: openjdk:11
    volumes:
      - ./discovery/build/libs:/app
    ports:
      - "8761:8761"
    command: java -jar /app/discovery-0.0.1-SNAPSHOT.jar
    networks:
      - my_network
  admin-server-service:
    image: openjdk:11
    volumes:
      - ./admin-server/build/libs:/app
    ports:
      - "9090:9090"
    command: java -jar /app/admin-server-0.0.1-SNAPSHOT.jar
    networks:
      - my_network
  gateway-service:
    image: openjdk:11
    volumes:
      - ./gateway/build/libs:/app
    ports:
      - "8080:8080"
    command: java -jar /app/gateway-0.0.1-SNAPSHOT.jar
    networks:
      - my_network
  to-do-list-service:
    image: openjdk:11
    volumes:
      - ./todolist/build/libs/todolist-0.0.1-SNAPSHOT.jar:/app/todolist-0.0.1-SNAPSHOT.jar
      - ./docker/wait-for-it.sh:/wait-for-it.sh
    ports:
      - "9001:9001"
    entrypoint: ["/wait-for-it.sh", "db:3306", "--", "java", "-jar", "/app/todolist-0.0.1-SNAPSHOT.jar"]
    networks:
      - my_network
  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskdb
    networks:
      - my_network

networks:
  my_network:
    external:
      name: my_network