version: "3.7"
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - my_network
  grafana:
    image: grafana/grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
      - "./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources"
      - "./docker/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards"
    ports:
      - "3000:3000"
    networks:
      - my_network
    depends_on:
      - prometheus
  keycloak:
    image: jboss/keycloak:latest
    volumes:
      - ./docker/keycloak:/opt/jboss/keycloak/imports
    command:
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/app-realm.json -Dkeycloak.profile.feature.upload_scripts=enabled"
    environment:
      DB_VENDOR: H2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    restart: always
    ports:
      - 8080:8080
    networks:
      - my_network
  eureka-discovery-service:
    image: openjdk:11
    volumes:
      - ./discovery/build/libs:/app
    ports:
      - "8761:8761"
    command: java -jar /app/discovery-0.0.1-SNAPSHOT.jar
    networks:
      - my_network
  admin-server-service:
    image: openjdk:11
    volumes:
      - ./admin-server/build/libs:/app
      - ./docker/wait-for-it.sh:/wait-for-it.sh
    ports:
      - "9000:9000"
    entrypoint: [ "/wait-for-it.sh", "eureka-discovery-service:8761", "--", "java", "-jar", "/app/admin-server-0.0.1-SNAPSHOT.jar" ]
    depends_on:
      - eureka-discovery-service
    networks:
      - my_network
  gateway-service:
    image: openjdk:11
    volumes:
      - ./gateway/build/libs:/app
      - ./docker/wait-for-it.sh:/wait-for-it.sh
    ports:
      - "8090:8090"
    entrypoint: ["/wait-for-it.sh", "eureka-discovery-service:8761", "--", "java", "-jar", "/app/gateway-0.0.1-SNAPSHOT.jar"]
    depends_on:
      - eureka-discovery-service
    networks:
      - my_network
  to-do-list-service:
    image: openjdk:11
    volumes:
      - ./todolist/build/libs/todolist-0.0.1-SNAPSHOT.jar:/app/todolist-0.0.1-SNAPSHOT.jar
      - ./docker/wait-for-it.sh:/wait-for-it.sh
    ports:
      - "10000:10000"
    entrypoint: ["/wait-for-it.sh", "db:3306", "eureka-discovery-service:8761", "--", "java", "-jar", "/app/todolist-0.0.1-SNAPSHOT.jar"]
    depends_on:
      - db
      - eureka-discovery-service
    networks:
      - my_network
  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskdb
    networks:
      - my_network

networks:
  my_network:
      name: my_network
