version: "3.7"
services:
  eureka-discovery-service:
    image: openjdk:11
    volumes:
      - ./discovery/build/libs:/app
    ports:
      - "8761:8761"
    command: java -jar /app/discovery-0.0.1-SNAPSHOT.jar
    networks:
      - my_network

networks:
  my_network:
    external:
      name: my_network